### ISSUE TITLE
THIS IS A MALWARE ! 

### ISSUE THREAD

**Issue by gggaming373** [Darkempire78/Discord-Tools#54]
so i was searching for a syntax higlighting for discord.py and i installed this and then kaspersky said that this is a malware? the file that it found malware was this js file https://github.com/Darkempire78/Discord-Tools/blob/master/src/grabDiscordToken.js (this is the source code of the vs code extension that i downloaded not my file) how much danger am i in can someone who is good with js can answer me pls

**Comment by Darkempire78** [comment]
Hello, I am the creator of the extension.  Indeed, this file is now considered a malware which seems logical.  This file automatically recovers your discord token.  The token is used to be able to communicate from VSC with Discord (this is a feature present in the extension).  However, to do this, the extension goes through your cookies in your browser to find the discord token.  This kind of thing is often used to steal discord accounts.  Here this is not the case because the token remains on the computer and is never sent anywhere.  It is therefore not a virus (you can check the code) but it uses a behavior often used by viruses.  

If you have other questions, do not hesitate!

**Comment by xanat0s** [comment]
this is information that should be disclosed in the readme for this project. people shouldn't have to dig thru _closed_ issues to find this information
