### ISSUE TITLE
Is it a Discord Token Grabber?

### ISSUE THREAD

**Issue by bestgoodgameYt** [Darkempire78/Discord-Tools#63]
Here is proof: 

https://github.com/Darkempire78/Discord-Tools/blob/master/src/grabDiscordToken.js
https://github.com/Darkempire78/Discord-Token-Grabber/blob/main/index.js

**Comment by lxi1400** [comment]
Have you even read the code you linked to?

**Comment by bestgoodgameYt** [comment]
Well people on the reviews even say it is,
 
![image](https://github.com/Darkempire78/Discord-Tools/assets/65880508/eda7dc26-b675-4cfb-b192-7bb8c200313d)
![image](https://media.discordapp.net/attachments/592101272208015376/987752974090641528/unknown.png)

**Comment by bestgoodgameYt** [comment]
So i just checked and that "Kaspersky" was the only one that though it was 
https://www.virustotal.com/gui/file/52535850646ecc2dee7ac91a95e91186e3cb1b23b5cea116b319beb7cf0d45c6/detection

**Comment by clementwzk** [comment]
The token grabber is used to automatically retrieve your token which is required to connect to Discord. Without it you won't be able to use the discord chat in VSCode. So it's not hidden (see the code) and it's not dangerous either because the extension doesn't send it to a server or anywhere else, it's only stored locally. @bestgoodgameYt @lxi1400
